# Generated by Django 5.1.7 on 2025-09-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0002_region_actif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ville',
            name='frequence_livraison',
        ),
        migrations.AddField(
            model_name='ville',
            name='Delai_livraison_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ville',
            name='Delai_livraison_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='nom_region',
            field=models.CharField(default='CATHEDIS', max_length=100, unique=True),
        ),
    ]
