# Generated by Django 5.1.7 on 2025-09-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0003_remove_ville_frequence_livraison_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
                'ordering': ['nom'],
            },
        ),
    ]
