# Generated by Django 5.1.7 on 2025-09-06 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_etiquette', models.CharField(choices=[('article', 'Étiquette Article'), ('commande', 'Étiquette Commande'), ('livraison', 'Étiquette Livraison'), ('stock', 'Étiquette Stock')], default='article', max_length=20)),
                ('format_page', models.CharField(choices=[('A4', 'A4 (210x297mm)'), ('A5', 'A5 (148x210mm)'), ('A6', 'A6 (105x148mm)'), ('CUSTOM', 'Personnalisé')], default='A4', max_length=10)),
                ('largeur', models.FloatField(default=210, verbose_name='Largeur (mm)')),
                ('hauteur', models.FloatField(default=297, verbose_name='Hauteur (mm)')),
                ('code_type', models.CharField(choices=[('barcode', 'Code-barres'), ('qr', 'QR Code'), ('both', 'Les deux')], default='barcode', max_length=20)),
                ('code_size', models.IntegerField(default=80, verbose_name='Taille du code (mm)')),
                ('code_position', models.CharField(choices=[('center', 'Centre'), ('left', 'Gauche'), ('right', 'Droite')], default='center', max_length=20)),
                ('police_titre', models.CharField(default='Helvetica-Bold', max_length=50)),
                ('taille_titre', models.IntegerField(default=16)),
                ('police_texte', models.CharField(default='Helvetica', max_length=50)),
                ('taille_texte', models.IntegerField(default=12)),
                ('couleur_principale', models.CharField(default='#3B82F6', max_length=7, verbose_name='Couleur principale')),
                ('couleur_secondaire', models.CharField(default='#1E40AF', max_length=7, verbose_name='Couleur secondaire')),
                ('couleur_texte', models.CharField(default='#1F2937', max_length=7, verbose_name='Couleur du texte')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_etiquettes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Template d'étiquette",
                'verbose_name_plural': "Templates d'étiquettes",
                'ordering': ['-date_creation'],
                'permissions': [('can_manage_etiquette_templates', "Peut gérer les templates d'étiquettes"), ('can_view_etiquette_templates', "Peut voir les templates d'étiquettes")],
            },
        ),
        migrations.CreateModel(
            name='EtiquetteBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du lot')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('commande_id', models.CharField(blank=True, max_length=50, verbose_name='ID Commande')),
                ('nom_article', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'article")),
                ('client_nom', models.CharField(blank=True, max_length=200, verbose_name='Nom du client')),
                ('prefixe_reference', models.CharField(default='ETQ', max_length=20, verbose_name='Préfixe de référence')),
                ('suffixe_reference', models.CharField(blank=True, max_length=20, verbose_name='Suffixe de référence')),
                ('nombre_etiquettes', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='etiquettes_batches/')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches_etiquettes', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='etiquettes_pro.etiquettetemplate')),
            ],
            options={
                'verbose_name': "Lot d'étiquettes",
                'verbose_name_plural': "Lots d'étiquettes",
                'ordering': ['-date_creation'],
                'permissions': [('can_manage_etiquette_batches', "Peut gérer les lots d'étiquettes"), ('can_view_etiquette_batches', "Peut voir les lots d'étiquettes")],
            },
        ),
        migrations.CreateModel(
            name='Etiquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, verbose_name='Référence')),
                ('nom_article', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'article")),
                ('variante', models.CharField(blank=True, max_length=100, verbose_name='Variante')),
                ('commande_id', models.CharField(blank=True, max_length=50, verbose_name='ID Commande')),
                ('client_nom', models.CharField(blank=True, max_length=200, verbose_name='Nom du client')),
                ('code_data', models.TextField(verbose_name='Données du code')),
                ('code_generated', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('ready', 'Prête'), ('printed', 'Imprimée'), ('archived', 'Archivée')], default='draft', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_impression', models.DateTimeField(blank=True, null=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='etiquettes_pdf/')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquettes_creees', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquettes', to='etiquettes_pro.etiquettetemplate')),
            ],
            options={
                'verbose_name': 'Étiquette',
                'verbose_name_plural': 'Étiquettes',
                'ordering': ['-date_creation'],
                'permissions': [('can_manage_etiquettes', 'Peut gérer les étiquettes'), ('can_view_etiquettes', 'Peut voir les étiquettes'), ('can_print_etiquettes', 'Peut imprimer les étiquettes')],
            },
        ),
    ]
