# Generated by Django 5.1.7 on 2025-09-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquettes_pro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EtiquetteBatch',
        ),
    ]
