# Generated by Django 5.1.7 on 2025-09-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquettes_pro', '0002_remove_etiquette_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquettetemplate',
            name='code_height',
            field=models.IntegerField(default=25, verbose_name='Hauteur du code (mm)'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='code_quality',
            field=models.CharField(choices=[('standard', 'Standard (300 DPI)'), ('high', 'Haute qualité (600 DPI)'), ('ultra', 'Ultra qualité (4K)')], default='high', max_length=20, verbose_name='Qualité du code'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='code_width',
            field=models.IntegerField(default=80, verbose_name='Largeur du code (mm)'),
        ),
    ]
