# Generated by Django 5.1.7 on 2025-09-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquettes_pro', '0003_etiquettetemplate_code_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquettetemplate',
            name='border_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Couleur des bordures'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='border_enabled',
            field=models.BooleanField(default=True, verbose_name='Activer les bordures'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='border_radius',
            field=models.FloatField(default=2.0, verbose_name='Rayon des coins arrondis (mm)'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='border_width',
            field=models.FloatField(default=1.0, verbose_name='Épaisseur des bordures (mm)'),
        ),
    ]
