# Generated by Django 5.1.7 on 2025-09-07 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0012_alter_commande_payement'),
        ('etiquettes_pro', '0004_etiquettetemplate_border_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiquette',
            name='commande_id',
        ),
        migrations.AddField(
            model_name='etiquette',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etiquettes', to='commande.commande', verbose_name='Commande'),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='commande_id_legacy',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID Commande (Legacy)'),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='panier_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etiquettes', to='commande.panier', verbose_name='Article du panier'),
        ),
    ]
