# Generated by Django 5.1.7 on 2025-09-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquettes_pro', '0005_remove_etiquette_commande_id_etiquette_commande_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiquette',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='etiquette',
            name='commande_id_legacy',
        ),
        migrations.RemoveField(
            model_name='etiquette',
            name='panier_item',
        ),
        migrations.AddField(
            model_name='etiquette',
            name='commande_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID Commande'),
        ),
    ]
