# Generated by Django 5.1.7 on 2025-09-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquettes_pro', '0006_remove_etiquette_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquette',
            name='cart_items',
            field=models.JSONField(blank=True, null=True, verbose_name='Articles du panier'),
        ),
    ]
