# Generated by Django 5.1.7 on 2025-09-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquettes_pro', '0007_etiquette_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquettetemplate',
            name='icone_adresse',
            field=models.CharField(default='fas fa-map-marker-alt', max_length=50, verbose_name='Icône adresse'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='icone_article',
            field=models.CharField(default='fas fa-box', max_length=50, verbose_name='Icône article'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='icone_client',
            field=models.CharField(default='fas fa-user', max_length=50, verbose_name='Icône client'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='icone_code',
            field=models.CharField(default='fas fa-barcode', max_length=50, verbose_name='Icône code'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='icone_date',
            field=models.CharField(default='fas fa-calendar-alt', max_length=50, verbose_name='Icône date'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='icone_marque',
            field=models.CharField(default='fas fa-crown', max_length=50, verbose_name='Icône marque'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='icone_panier',
            field=models.CharField(default='fas fa-shopping-cart', max_length=50, verbose_name='Icône panier'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='icone_prix',
            field=models.CharField(default='fas fa-money-bill-wave', max_length=50, verbose_name='Icône prix'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='icone_telephone',
            field=models.CharField(default='fas fa-phone', max_length=50, verbose_name='Icône téléphone'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='icone_ville',
            field=models.CharField(default='fas fa-building', max_length=50, verbose_name='Icône ville'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='icone_website',
            field=models.CharField(default='fas fa-globe', max_length=50, verbose_name='Icône website'),
        ),
    ]
