# Generated by Django 5.1.7 on 2025-09-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquettes_pro', '0008_etiquettetemplate_icone_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_code_height',
            field=models.IntegerField(default=80, verbose_name='Hauteur code impression (px)'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_code_width',
            field=models.IntegerField(default=250, verbose_name='Largeur code impression (px)'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_contact_width',
            field=models.IntegerField(default=250, verbose_name='Largeur section contact (px)'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_font_size_small',
            field=models.IntegerField(default=10, verbose_name='Taille police petit texte impression'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_font_size_text',
            field=models.IntegerField(default=12, verbose_name='Taille police texte impression'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_font_size_title',
            field=models.IntegerField(default=16, verbose_name='Taille police titre impression'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_margin_bottom',
            field=models.IntegerField(default=10, verbose_name='Marge bas (px)'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_margin_left',
            field=models.IntegerField(default=10, verbose_name='Marge gauche (px)'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_margin_right',
            field=models.IntegerField(default=10, verbose_name='Marge droite (px)'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_margin_top',
            field=models.IntegerField(default=10, verbose_name='Marge haut (px)'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_padding',
            field=models.IntegerField(default=15, verbose_name='Espacement interne (px)'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_show_articles',
            field=models.BooleanField(default=True, verbose_name='Afficher la liste des articles'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_show_brand',
            field=models.BooleanField(default=True, verbose_name='Afficher la marque YOZAK'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_show_client_info',
            field=models.BooleanField(default=True, verbose_name='Afficher les infos client'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_show_contact_info',
            field=models.BooleanField(default=True, verbose_name='Afficher les infos de contact'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_show_date',
            field=models.BooleanField(default=True, verbose_name='Afficher la date'),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_show_prices',
            field=models.BooleanField(default=True, verbose_name="Afficher les prix à l'impression"),
        ),
        migrations.AddField(
            model_name='etiquettetemplate',
            name='print_show_total_circle',
            field=models.BooleanField(default=True, verbose_name='Afficher le cercle total articles'),
        ),
    ]
