# Generated by Django 5.1.7 on 2025-09-08 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0012_alter_commande_payement'),
        ('etiquettes_pro', '0009_etiquettetemplate_print_code_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiquette',
            name='commande_id',
        ),
        migrations.AddField(
            model_name='etiquette',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etiquettes', to='commande.commande', verbose_name='Commande associée'),
        ),
    ]
