# Generated by Django 5.1.7 on 2025-09-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquettes_pro', '0010_remove_etiquette_commande_id_etiquette_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiquette',
            name='commande',
        ),
        migrations.AddField(
            model_name='etiquette',
            name='commande_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ID Commande'),
        ),
    ]
