# Generated by Django 5.1.7 on 2025-09-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquettes_pro', '0011_remove_etiquette_commande_etiquette_commande_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquettetemplate',
            name='format_page',
            field=models.CharField(choices=[('A4', 'A4 (210x297mm)'), ('A5', 'A5 (148x210mm)'), ('A6', 'A6 (105x148mm)'), ('10x10', '10x10 cm (100x100mm)'), ('CUSTOM', 'Personnalisé')], default='10x10', max_length=10),
        ),
        migrations.AlterField(
            model_name='etiquettetemplate',
            name='hauteur',
            field=models.FloatField(default=100, verbose_name='Hauteur (mm)'),
        ),
        migrations.AlterField(
            model_name='etiquettetemplate',
            name='largeur',
            field=models.FloatField(default=100, verbose_name='Largeur (mm)'),
        ),
    ]
