# Generated by Django 5.1.7 on 2025-09-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquettes_pro', '0012_alter_etiquettetemplate_format_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquettetemplate',
            name='format_page',
            field=models.CharField(choices=[('10x10', '10x10 cm (100x100mm)'), ('CUSTOM', 'Personnalisé')], default='10x10', max_length=10),
        ),
    ]
