# Generated by Django 5.1.7 on 2025-09-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquettes_pro', '0013_alter_etiquettetemplate_format_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquette',
            name='compteur_impression_qr',
            field=models.PositiveIntegerField(default=0, verbose_name='Compteur impression QR'),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='compteur_impression_ticket',
            field=models.PositiveIntegerField(default=0, verbose_name='Compteur impression ticket'),
        ),
    ]
