# Generated by Django 5.1.7 on 2025-09-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0007_set_commande_id_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='source',
            field=models.CharField(blank=True, choices=[('Appel', 'Appel'), ('Whatsapp ', 'Whatsapp '), ('SMS', 'SMS'), ('Email', 'Email'), ('Facebook', 'Facebook'), ('Youcan', 'Youcan'), ('Shopify', 'Shopify')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='commentaire',
            field=models.TextField(blank=True, choices=[('Appel 1', 'Appel 1'), ('Appel 2', 'Appel 2'), ('Appel 3', 'Appel 3'), ('Appel 4', 'Appel 4'), ('Appel 5', 'Appel 5'), ('Appel 6', 'Appel 6'), ('Client intéressé', 'Client intéressé'), ('Confirmée', 'Confirmée'), ('Confirmée & Echangée', 'Confirmée & Echangée'), ('Echangée', 'Echangée'), ('Abonnement', 'Abonnement'), ('Reduction', 'Reduction'), ('Client hésitant', 'Client hésitant')], null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('APPEL', 'Appel '), ('Appel Whatsapp', 'Appel Whatsapp'), ('Message Whatsapp', 'Appel Whatsapp '), ('Vocal Whatsapp', 'Vocal Whatsapp '), ('ENVOI_SMS', 'Envoi de SMS')], max_length=30),
        ),
    ]
