# Generated by Django 5.1.7 on 2025-09-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0008_commande_source_alter_operation_commentaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='is_upsell',
        ),
    ]
