# Generated by Django 5.1.7 on 2025-09-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0009_remove_commande_is_upsell'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='payement',
            field=models.BooleanField(choices=[('Non payé', 'Non payé'), ('Payé', 'Payé'), ('Remboursée', 'Remboursée')], default=False, verbose_name='Payement'),
        ),
    ]
