# Generated by Django 5.1.7 on 2025-09-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0010_commande_payement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='payement',
            field=models.CharField(choices=[('Non payé', 'Non payé'), ('Payé', 'Payé'), ('Remboursée', 'Remboursée')], default=False, verbose_name='Payement'),
        ),
    ]
