# Generated by Django 5.1.7 on 2025-09-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0012_alter_commande_payement'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('width', models.FloatField(default=180, verbose_name='Largeur (mm)')),
                ('height', models.FloatField(default=260, verbose_name='Hauteur (mm)')),
                ('margin_top', models.FloatField(default=10, verbose_name='Marge haute (mm)')),
                ('margin_bottom', models.FloatField(default=10, verbose_name='Marge basse (mm)')),
                ('margin_left', models.FloatField(default=10, verbose_name='Marge gauche (mm)')),
                ('margin_right', models.FloatField(default=10, verbose_name='Marge droite (mm)')),
                ('font_family', models.CharField(default='Helvetica', max_length=50, verbose_name='Police')),
                ('font_size_title', models.IntegerField(default=16, verbose_name='Taille police titre')),
                ('font_size_text', models.IntegerField(default=12, verbose_name='Taille police texte')),
                ('font_size_barcode', models.IntegerField(default=14, verbose_name='Taille police code-barres')),
                ('color_header', models.CharField(default='#2c3e50', max_length=7, verbose_name='Couleur en-tête')),
                ('color_footer', models.CharField(default='#2c3e50', max_length=7, verbose_name='Couleur pied')),
                ('color_text', models.CharField(default='#333333', max_length=7, verbose_name='Couleur texte')),
                ('barcode_width', models.FloatField(default=4, verbose_name='Largeur barres (mm)')),
                ('barcode_height', models.FloatField(default=80, verbose_name='Hauteur barres (mm)')),
                ('barcode_format', models.CharField(default='CODE128B', max_length=20, verbose_name='Format code-barres')),
                ('qr_size', models.IntegerField(default=300, verbose_name='Taille QR code (px)')),
                ('show_header', models.BooleanField(default=True, verbose_name='Afficher en-tête')),
                ('show_footer', models.BooleanField(default=True, verbose_name='Afficher pied')),
                ('show_barcode', models.BooleanField(default=True, verbose_name='Afficher code-barres')),
                ('show_qr', models.BooleanField(default=False, verbose_name='Afficher QR code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Template d'étiquette",
                'verbose_name_plural': "Templates d'étiquettes",
                'ordering': ['-created_at'],
            },
        ),
    ]
