# Generated by Django 5.1.7 on 2025-09-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0012_alter_commande_payement'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='frais_livraison',
            field=models.BooleanField(default=False, verbose_name='Frais de livraison'),
        ),
    ]
