# Generated by Django 5.1.7 on 2025-09-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0014_commande_frais_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatcommande',
            name='date_fin_confirmation_delayed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin de confirmation décalée'),
        ),
    ]
