# Generated by Django 5.1.7 on 2025-09-08 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0015_etatcommande_date_fin_confirmation_delayed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etatcommande',
            old_name='date_fin_confirmation_delayed',
            new_name='date_fin_delayed',
        ),
    ]
