# Generated by Django 5.1.7 on 2025-09-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0016_rename_date_fin_confirmation_delayed_etatcommande_date_fin_delayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='Date_livraison',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='frais_livraison',
            field=models.BooleanField(default=True, verbose_name='Frais de livraison'),
        ),
        migrations.AlterField(
            model_name='etatcommande',
            name='date_fin_delayed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date reporte de confirmation décalée'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='commentaire',
            field=models.TextField(blank=True, choices=[('Appel 1', 'Appel 1'), ('Appel 2', 'Appel 2'), ('Appel 3', 'Appel 3'), ('Appel 4', 'Appel 4'), ('Appel 5', 'Appel 5'), ('Appel 6', 'Appel 6'), ('Confirmée', 'Confirmée'), ('Confirmée & Echangée', 'Confirmée & Echangée'), ('Echangée', 'Echangée'), ('Abonnement', 'Abonnement'), ('Offre', 'Offre'), ('numero errone', 'numéro erroné'), ('boite vocalee', 'boite vocalee'), ('indisponible', 'indisponible')], null=True),
        ),
    ]
