# Generated by Django 5.1.7 on 2025-09-12 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_prix_remise_1_article_prix_remise_2_and_more'),
        ('commande', '0017_commande_date_livraison_and_more'),
        ('parametre', '0004_livreur'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRetourne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_retournee', models.PositiveIntegerField(help_text='Quantité retournée de cet article/variante')),
                ('prix_unitaire_origine', models.DecimalField(decimal_places=2, help_text="Prix unitaire de l'article au moment de la livraison partielle", max_digits=10)),
                ('raison_retour', models.TextField(blank=True, help_text='Raison du retour (optionnel)', max_length=500)),
                ('date_retour', models.DateTimeField(auto_now_add=True, help_text='Date et heure du retour')),
                ('statut_retour', models.CharField(choices=[('en_attente', 'En attente de traitement'), ('reintegre_stock', 'Réintégré en stock'), ('renvoye_preparation', 'Renvoyé en préparation'), ('defectueux', 'Défectueux - à écarter'), ('traite', 'Traité')], default='en_attente', help_text='Statut du traitement du retour', max_length=50)),
                ('date_traitement', models.DateTimeField(blank=True, help_text='Date de traitement du retour', null=True)),
                ('commentaire_traitement', models.TextField(blank=True, help_text='Commentaire sur le traitement du retour', max_length=500)),
                ('article', models.ForeignKey(help_text='Article retourné', on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('commande', models.ForeignKey(help_text="Commande d'origine de l'article retourné", on_delete=django.db.models.deletion.CASCADE, related_name='articles_retournes', to='commande.commande')),
                ('operateur_retour', models.ForeignKey(blank=True, help_text='Opérateur qui a effectué le retour', null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametre.operateur')),
                ('operateur_traitement', models.ForeignKey(blank=True, help_text='Opérateur qui a traité le retour', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours_traites', to='parametre.operateur')),
                ('variante', models.ForeignKey(blank=True, help_text="Variante spécifique de l'article retourné", null=True, on_delete=django.db.models.deletion.CASCADE, to='article.variantearticle')),
            ],
            options={
                'verbose_name': 'Article Retourné',
                'verbose_name_plural': 'Articles Retournés',
                'ordering': ['-date_retour'],
                'indexes': [models.Index(fields=['commande', 'statut_retour'], name='commande_ar_command_5eb375_idx'), models.Index(fields=['article', 'statut_retour'], name='commande_ar_article_afd401_idx'), models.Index(fields=['date_retour'], name='commande_ar_date_re_491d3d_idx')],
            },
        ),
    ]
