# Generated by Django 5.1.7 on 2025-09-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0018_articleretourne'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='remise_appliquer',
            field=models.BooleanField(default=False),
        ),
    ]
