# Generated by Django 5.1.7 on 2025-09-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0019_panier_remise_appliquer'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='type_remise_appliquee',
            field=models.CharField(blank=True, choices=[('', 'Aucune remise'), ('remise_1', 'Prix remise 1'), ('remise_2', 'Prix remise 2'), ('remise_3', 'Prix remise 3'), ('remise_4', 'Prix remise 4')], default='', max_length=20),
        ),
    ]
