# Generated by Django 5.1.7 on 2025-09-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0020_panier_type_remise_appliquee'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='Date_paiement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
    ]
