# Generated by Django 5.1.7 on 2025-10-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0021_commande_date_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='type_prix_gele',
            field=models.CharField(blank=True, choices=[('', 'Non défini'), ('normal', 'Prix normal'), ('promotion', 'Prix promotion'), ('liquidation', 'Prix liquidation'), ('test', 'Prix test'), ('upsell_niveau_1', 'Upsell niveau 1'), ('upsell_niveau_2', 'Upsell niveau 2'), ('upsell_niveau_3', 'Upsell niveau 3'), ('upsell_niveau_4', 'Upsell niveau 4'), ('remise_1', 'Prix remise 1'), ('remise_2', 'Prix remise 2'), ('remise_3', 'Prix remise 3'), ('remise_4', 'Prix remise 4')], default='', max_length=30, verbose_name='Type de prix gelé'),
        ),
    ]
