# Generated by Django 5.1.7 on 2025-10-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0022_panier_type_prix_gele'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='prix_panier',
            field=models.FloatField(default=0),
        ),
    ]
