# Generated by Django 5.1.7 on 2025-10-17 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0023_panier_prix_panier'),
        ('parametre', '0004_livreur'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemisePanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_remise', models.CharField(choices=[('POURCENTAGE', 'Pourcentage'), ('MONTANT_FIXE', 'Montant fixe')], default='POURCENTAGE', max_length=20, verbose_name='Type de remise')),
                ('valeur_remise', models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage (ex: 10.5 pour 10.5%) ou montant fixe (ex: 50.00 DH)', max_digits=10, verbose_name='Valeur de la remise')),
                ('montant_applique', models.DecimalField(decimal_places=2, default=0, help_text='Montant en DH réellement déduit du sous-total du panier', max_digits=10, verbose_name='Montant déduit')),
                ('raison_remise', models.CharField(blank=True, help_text="Motif ou justification de l'application de cette remise", max_length=255, null=True, verbose_name='Raison de la remise')),
                ('date_application', models.DateTimeField(auto_now_add=True, verbose_name="Date d'application")),
                ('operateur', models.ForeignKey(blank=True, help_text='Opérateur qui a appliqué cette remise', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remises_paniers_appliquees', to='parametre.operateur', verbose_name='Opérateur')),
                ('panier', models.OneToOneField(help_text='Panier auquel cette remise est appliquée', on_delete=django.db.models.deletion.CASCADE, related_name='remise_personnalisee', to='commande.panier', verbose_name='Panier')),
            ],
            options={
                'verbose_name': 'Remise personnalisée de panier',
                'verbose_name_plural': 'Remises personnalisées de paniers',
                'ordering': ['-date_application'],
            },
        ),
    ]
