# Generated by Django 5.1.7 on 2025-10-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0024_remisepanier'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='sous_total_remise',
            field=models.FloatField(default=0),
        ),
    ]
