# Generated by Django 5.1.7 on 2025-11-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0025_panier_sous_total_remise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('APPEL', 'Appel'), ('Appel Whatsapp', 'Appel WhatsApp'), ('Message Whatsapp', 'Message WhatsApp'), ('Vocal Whatsapp', 'Vocal WhatsApp'), ('ENVOI_SMS', 'Envoi de SMS')], max_length=30),
        ),
    ]

# Generated by Django 5.1.7 on 2025-11-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0025_panier_sous_total_remise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('APPEL', 'Appel'), ('Appel Whatsapp', 'Appel WhatsApp'), ('Message Whatsapp', 'Message WhatsApp'), ('Vocal Whatsapp', 'Vocal WhatsApp'), ('ENVOI_SMS', 'Envoi de SMS')], max_length=30),
        ),
    ]
