# Generated by Django 4.2.25 on 2025-10-21 17:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('reference', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('modele', models.IntegerField(blank=True, null=True, unique=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prix_actuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phase', models.CharField(choices=[('EN_COURS', 'En Cours'), ('LIQUIDATION', 'Liquidation'), ('EN_TEST', 'En Test'), ('PROMO', 'Promo')], default='EN_COURS', max_length=20, verbose_name="Phase de l'article")),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('image_url', models.URLField(blank=True, help_text='Lien direct vers une image externe (ex: Unsplash)', null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('isUpsell', models.BooleanField(default=False, verbose_name='Est un upsell')),
                ('prix_upsell_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix upsell 1')),
                ('prix_upsell_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix upsell 2')),
                ('prix_upsell_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix upsell 3')),
                ('prix_upsell_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix upsell 4')),
                ('Prix_liquidation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix liquidation')),
                ('prix_remise_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix remise 1')),
                ('prix_remise_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix remise 2')),
                ('prix_remise_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix remise 3')),
                ('prix_remise_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix remise 4')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['nom', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('SANDALES', 'Sandales'), ('SABOT', 'Sabot'), ('CHAUSSURES', 'Chaussures'), ('ESPARILLE', 'Espadrilles'), ('BASKET', 'Baskets'), ('MULES', 'Mules'), ('PACK_SAC', 'Pack Sac'), ('BOTTE', 'Bottes'), ('ESCARPINS', 'Escarpins')], default='', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('code_hex', models.CharField(blank=True, help_text='Code couleur hexadécimal (ex: #FF0000)', max_length=7, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Couleur',
                'verbose_name_plural': 'Couleurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme'), ('FILLE', 'Fille'), ('GARCON', 'Garçon')], default='', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Pointure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointure', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage des pointures")),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pointure',
                'verbose_name_plural': 'Pointures',
                'ordering': ['ordre', 'pointure'],
            },
        ),
        migrations.CreateModel(
            name='VarianteArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_variante', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('qte_disponible', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='article.article')),
                ('couleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.couleur')),
                ('pointure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.pointure')),
            ],
            options={
                'verbose_name': "Variante d'article",
                'verbose_name_plural': "Variantes d'articles",
                'ordering': ['article__nom', 'couleur__nom', 'pointure__pointure'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('pourcentage_reduction', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(blank=True, limit_choices_to={'phase': 'EN_COURS'}, related_name='promotions', to='article.article')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-date_debut', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement_pos', 'Ajustement Positif'), ('ajustement_neg', 'Ajustement Négatif'), ('inventaire', 'Inventaire'), ('retour_client', 'Retour Client')], max_length=20)),
                ('quantite', models.IntegerField(help_text='Quantité du mouvement. Positive pour une entrée, négative pour une sortie.')),
                ('qte_apres_mouvement', models.IntegerField()),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='article.article')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
