# Generated by Django 4.2.25 on 2025-10-21 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        ('parametre', '0001_initial'),
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='commande_associee',
            field=models.ForeignKey(blank=True, help_text='Commande liée à ce mouvement (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='commande.commande'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametre.operateur'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='article.variantearticle'),
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.categorie'),
        ),
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.genre', verbose_name='Genre'),
        ),
        migrations.AlterUniqueTogether(
            name='variantearticle',
            unique_together={('article', 'couleur', 'pointure')},
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(check=models.Q(('date_fin__gt', models.F('date_debut'))), name='date_fin_apres_debut'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(check=models.Q(('prix_unitaire__gt', 0)), name='prix_unitaire_positif'),
        ),
    ]
