# Generated by Django 5.1.7 on 2025-09-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Prix_liquidation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix liquidation'),
        ),
        migrations.AddField(
            model_name='article',
            name='prix_uspell_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix upsell final'),
        ),
    ]
