# Generated by Django 5.1.7 on 2025-09-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_prix_liquidation_article_prix_uspell_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='prix_uspell_final',
        ),
    ]
