# Generated by Django 5.1.7 on 2025-09-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_article_prix_uspell_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prix_remise_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix remise 1'),
        ),
        migrations.AddField(
            model_name='article',
            name='prix_remise_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix remise 2'),
        ),
        migrations.AddField(
            model_name='article',
            name='prix_remise_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix remise 3'),
        ),
        migrations.AddField(
            model_name='article',
            name='prix_remise_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix remise 4'),
        ),
    ]
