# Generated by Django 5.1.7 on 2025-11-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_prix_remise_1_article_prix_remise_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='prix_remise_1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='prix_remise_2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='prix_remise_3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='prix_remise_4',
        ),
        migrations.RemoveField(
            model_name='article',
            name='prix_upsell_1',
        ),
        migrations.AddField(
            model_name='article',
            name='prix_gros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix upsell 4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_upsell_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix upsell 1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_upsell_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix upsell 2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_upsell_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix upsell 3'),
        ),
    ]
